# Simple workflow for deploying static content to preview GitHub Pages
name: Deploy static content to preview Pages

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: write          # Required for pr-preview-action
  contents: write         # Required for the checkout action to know to kick off (read) and pr-preview-action (write)
  deployments: write      # Required for pr-preview-action
  id-token: write         # Required for pr-preview-action
  pages: write            # Required for pr-preview-action
  pull-requests: write    # Required for pr-preview-action

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-page:
    runs-on: ubuntu-latest
    name: Build GitHub Pages preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./src/
