# Simple workflow for deploying static content to preview GitHub Pages
name: Deploy static content to preview Pages

on:
  push:
    branches: ["feature/*"]

  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - closed
  #   paths:
  #     - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: write          # Required for pr-preview-action
  contents: write         # Required for the checkout action to know to kick off (read) and pr-preview-action (write)
  deployments: write      # Required for pr-preview-action
  id-token: write         # Required for pr-preview-action
  pages: write            # Required for pr-preview-action
  pull-requests: write    # Required for pr-preview-action

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

env:
  PREVIEW_BRANCH: gh-pages

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rossjrw/pr-preview-action@v1
        id: preview-step
        with:
          source-dir: ./src/
          preview-branch: ${{ env.PREVIEW_BRANCH }}
